name: Interactive SSH Runner (JuiceSSH)

on:
  workflow_dispatch:

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maximize Disk Space & Swap
        uses: easimon/maximize-build-space@v5
        with:
          swap-size-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Setup Tmate SSH Session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false # Menjaga terminal tetap aktif & tidak langsung selesai
          
